Person List Component #302
unlcms/project-herbie pull request #313
Opened 2023-03-13 22:11 UTC by sarongebre

2023-03-24 14:22 UTC, ericras commented on web/modules/custom/unl_person/templates/unl-person-person-list.html.twig
> +{# <div{{ attributes }}>
This file is totally commented out?

2023-03-24 14:24 UTC, ericras commented on web/themes/custom/unl_five_herbie/templates/node/node--person--teaser-featured.html.twig
> +{{ attach_library('classy/node') }}
We used to just attach this because Drupal default theme did.  I believe "classy" base theme has been removed in 10 so this probably generates an error or a notice in the log.  I think this can be removed

2023-03-24 15:46 UTC, sarongebre commented on web/themes/custom/unl_five_herbie/templates/node/node--person--teaser-featured.html.twig
> +{{ attach_library('classy/node') }}
Okay

2023-03-24 15:59 UTC, sarongebre commented on web/modules/custom/unl_person/templates/unl-person-person-list.html.twig
> +{# <div{{ attributes }}>
Yes, I have a question about that.

2023-03-24 16:06 UTC, sarongebre commented on web/themes/custom/unl_five_herbie/templates/block/unl-person-person-list.html.twig
> +<ol {{orderedListAttribute}}>
Yes, that can be changed. I am not sure why I created that in the first place hehe. Looks like this now -
<img width="444" alt="image" src="https://user-images.githubusercontent.com/72580736/227579814-3e582aa9-9629-4d98-8473-b0e0a655d278.png">

2023-03-24 16:09 UTC, sarongebre commented on web/themes/custom/unl_five_herbie/templates/node/node--person--teaser-featured.html.twig
> +{{ attach_library('classy/node') }}
Removed

2023-03-24 16:09 UTC, sarongebre commented on web/themes/custom/unl_five_herbie/templates/block/unl-person-person-list.html.twig
> +<ol {{orderedListAttribute}}>
Changed

2023-04-05 18:40 UTC, ericras requested changes

2023-04-05 18:40 UTC, ericras commented on config/sync/core.extension.yml
> +  dcf_classes: 0
There shouldn't be any changes to this file. Remove dcf_classes.

2023-04-05 18:40 UTC, ericras commented on config/sync/core.extension.yml
> -  infotext: 0
There shouldn't be any changes to this file. Add this back in.

2023-04-05 18:40 UTC, ericras commented on config/sync/dcf_classes.classes.yml
> +heading:
This file should no longer exist. This module was removed.

2023-04-05 18:40 UTC, ericras commented on config/sync/views.view.content.yml
> +            group_items: {  }
This file shouldn't be changed.  This was removed in 2dd4bca

2023-04-05 18:40 UTC, ericras commented on config/sync/views.view.media_library.yml
> +            group_items: {  }
This file shouldn't be changed.  This was removed in 952e9ab

2023-04-05 18:40 UTC, ericras commented on config/sync/views.view.media.yml
> +        - user
This file shouldn't be changed. It was last updated in 2335f79

2023-04-05 18:40 UTC, ericras commented on web/themes/custom/unl_five_herbie/css/theme/person.css
>  @charset "UTF-8";@font-face{font-family:directory-icon;src:url(../../font/directory-icon.woff2?63491384) format('woff2'),url(../../font/directory-icon.woff?63491384) format('woff');font-weight:400;fo
All this CSS from directory.unl.edu can be removed. I'm pretty sure its not needed any more with the new designs.

2023-04-05 18:40 UTC, ericras commented on config/sync/layout_builder_styles.group.container.yml
> -uuid: 1be5bd18-96c1-48d4-bbb1-a7eed18f7a03
All of these config/sync/layout_builder_styles* files should still be here.

2023-04-05 18:40 UTC, ericras commented on config/sync/field.storage.node.s_n_page_options.yml
> -uuid: 7655cec9-9b5d-4e98-8682-2cd081e81529
This file should not be deleted.

2023-04-05 18:40 UTC, ericras commented on config/sync/field.field.node.builder_page.s_n_page_options.yml
> -uuid: b033731d-8f5f-4e9c-b051-f26dd0df9c40
This file should not be deleted.

2023-04-05 18:40 UTC, ericras commented on config/sync/field.field.media.image.field_media_image.yml
>    max_resolution: 5000x5000
This file shouldn't change.

2023-04-05 18:40 UTC, ericras commented on config/sync/field.field.media.file.field_media_file.yml
> +  file_directory: '[date:custom:Y]-[date:custom:m]'
This file shouldn't change.

2023-04-05 18:40 UTC, ericras commented on config/sync/core.entity_form_display.node.builder_page.default.yml
>      - field.field.node.builder_page.body
This file shouldn't have changed.

2023-04-05 21:21 UTC, ericras requested changes

2023-04-05 21:21 UTC, ericras commented on web/themes/custom/unl_five_herbie/templates/node/node--person--full.html.twig
> +												<a class="dcf-d-block dcf-h-6 dcf-w-6" href="https://www.facebook.com/{{ node.n_person_social_fb.value }}" aria-label="Jane Doe on Facebook">
All the instances of "Jane Doe" needs replacing with their name

2023-04-05 21:21 UTC, ericras commented on config/sync/field.storage.node.n_person_address.yml
> +cardinality: 5
I don't think this should have changed. The Address override only has 4 lines.

2023-04-05 21:21 UTC, ericras commented on config/sync/core.entity_form_display.node.person.default.yml
> +        - n_person_social_pinterest
On /admin/structure/types/manage/person/form-display/ list the social media fields in the order that they are rendered.  Facebook first, twitter second, etc.

2023-04-05 21:21 UTC, ericras commented on config/sync/field.field.node.person.n_person_social_linkedin.yml
> +description: ''
The LinkedIn field needs a description to help them with what to enter. The linkedin profile is a weird URL like https://www.linkedin.com/in/eric-rasmussen-0a6b7048/ so the help text could be something like "Enter everything that comes after 'https://www.linkedin.com/' from your profile's URL address."

2023-04-05 21:25 UTC, sarongebre commented on web/themes/custom/unl_five_herbie/templates/node/node--person--full.html.twig
> +												<a class="dcf-d-block dcf-h-6 dcf-w-6" href="https://www.facebook.com/{{ node.n_person_social_fb.value }}" aria-label="Jane Doe on Facebook">
Oh I totally missed that! I will change it!

2023-04-05 21:31 UTC, ericras commented
Follow up issue #339

2023-04-06 18:38 UTC, merged