Added webform autocomplete element
unlcms/project-herbie pull request #827
Opened 2024-09-12 17:40 UTC by sarongebre

Added Webform autocomplete element with support for predefined lists and YAML predefined list source configuration for developers. I've adjusted the permissions accordingly. Fixes #825.

2024-10-09 16:04 UTC, ericras requested changes

2024-10-09 16:04 UTC, ericras commented on web/modules/custom/unl_webform/unl_webform.permissions.yml
> +access webform options:
Can this be changed to "access unl webform options" to make sure we never have a collision with the main webform module in the future?

2024-10-09 16:07 UTC, ericras commented on web/modules/custom/unl_webform/src/Routing/RouteSubscriber.php
> +{
You might need to set your IDE to not change formatting like this when you save the file

2024-10-11 13:25 UTC, sarongebre commented on web/modules/custom/unl_webform/unl_webform.permissions.yml
> +access webform options:
Okay, I will change that

2024-10-11 13:25 UTC, sarongebre commented on web/modules/custom/unl_webform/src/Routing/RouteSubscriber.php
> +{
Okay.

2024-10-11 14:42 UTC, sarongebre commented on web/modules/custom/unl_webform/unl_webform.permissions.yml
> +access webform options:
I have made the change

2024-10-11 14:42 UTC, sarongebre commented on web/modules/custom/unl_webform/src/Routing/RouteSubscriber.php
> +{
I have made the change

2024-10-23 16:02 UTC, ericras approved these changes

2024-10-23 16:07 UTC, merged